### ISSUE TITLE
change_stream bring nothing

### ISSUE THREAD

**Issue by X-Gorn** [pytgcalls/pytgcalls#210]
**Describe the bug**
when trying to change the stream audio, it does nothing. it's just weird. when i stop the vc, it works again.

**To Reproduce**
await tgcalls.change_stream

**Expected behavior**
work

**Log**
If applicable, add logs on ultraverbose mode to help explain your problem.

**Linux (please complete the following information):**
 - OS: [e.g. Linux Mint 20.1]
 - NodeJS Version [e.g. 1.14]
 - Python Version [e.g. 3.9]

**Additional context**

**Comment by Laky-64** [comment]
What's your PyTgCalls version and NTgCalls version?

**Comment by X-Gorn** [comment]
pytgcalls v1.2.0
ntgcalls v.1.0.6

deployment on heroku.


Pada tanggal Rab, 7 Feb 2024 09.04, Laky64 ***@***.***>
menulis:

**Comment by Laky-64** [comment]
Fixed

**Comment by X-Gorn** [comment]
tried latest version, still the same thing happen. no errors. aka it does
not working.

Pada tanggal Rab, 7 Feb 2024 09.04, Laky64 ***@***.***>
menulis:

**Comment by Laky-64** [comment]
Can you join in our support group and tagging me @Laky64?

Support Group:
t.me/PyTgCallsChat
